{{- range $name, $cfg := .Values.persistentVolumes }}
{{- if $cfg.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "trembita-1.12.6-ss.fullname" $) $name }}
spec:
  accessModes:
    {{- range $cfg.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ $cfg.size }}
  {{- if $cfg.storageClassName }}
  storageClassName: {{ $cfg.storageClassName }}
  {{- end }}
---
{{- end }}
{{- end }}