apiVersion: v1
kind: Service
metadata:
  name: {{ include "trembita-1.12.6-ss.fullname" . }}
  labels:
    {{- include "trembita-1.12.6-ss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "trembita-1.12.6-ss.selectorLabels" . | nindent 4 }}
